create table if not exists users (
    id            bigint generated by default as identity primary key,
    email         varchar(255) not null unique,
    login         varchar(255) not null unique,
    name          varchar(255) not null,
    birthday      date         not null,
    created_at    timestamp    not null default current_timestamp
);

create table if not exists mpa_rating (
    id   smallint    primary key,
    code varchar(16) not null unique
);

create table if not exists genre (
    id   smallint     primary key,
    name varchar(64)  not null unique
);

create table if not exists films (
    id             bigint generated by default as identity primary key,
    name           varchar(255) not null,
    description    text         not null,
    release_date   date         not null,
    duration       integer      not null,
    mpa_rating_id  smallint     not null,
    created_at     timestamp    not null default current_timestamp,
    constraint fk_films_mpa
        foreign key (mpa_rating_id) references mpa_rating(id)
);

create table if not exists film_genre (
    film_id  bigint    not null,
    genre_id smallint  not null,
    constraint pk_film_genre primary key (film_id, genre_id),
    constraint fk_film_genre_film
        foreign key (film_id) references films(id) on delete cascade,
    constraint fk_film_genre_genre
        foreign key (genre_id) references genre(id) on delete cascade
);

create table if not exists friendship (
    requester_id bigint   not null,
    addressee_id bigint   not null,
    status       varchar(32) not null,
    created_at   timestamp not null default current_timestamp,
    constraint pk_friendship primary key (requester_id, addressee_id),
    constraint ck_friendship_self check (requester_id <> addressee_id),
    constraint fk_friendship_requester
        foreign key (requester_id) references users(id) on delete cascade,
    constraint fk_friendship_addressee
        foreign key (addressee_id) references users(id) on delete cascade
);

create table if not exists film_like (
    film_id    bigint   not null,
    user_id    bigint   not null,
    created_at timestamp default current_timestamp,
    constraint pk_film_like primary key (film_id, user_id),
    constraint fk_film_like_film
        foreign key (film_id) references films(id) on delete cascade,
    constraint fk_film_like_user
        foreign key (user_id) references users(id) on delete cascade
);

create index if not exists idx_films_mpa on films(mpa_rating_id);
create index if not exists idx_likes_user on film_like(user_id);
create index if not exists idx_film_genre_genre on film_genre(genre_id);
